#!/usr/bin/env python

Import('env')

src_files = [
   "customproperty.cpp",
   "entityinfo.cpp",
   "eventinfo.cpp",
   "inputcache.cpp",
   "inputdata.cpp",
   "inputinfo.cpp",
   "network.cpp",
   "nodespawner.cpp",
   "pinginfo.cpp",
   "playerdata.cpp",
   "playernode.cpp",
   "propcomparer.cpp",
   "register_types.cpp",
   "snapentity.cpp",
   "snapshot.cpp",
   "snapshotdata.cpp",
   "updtcontrol.cpp"
]

module_env = env.Clone()


for x in env.module_list:
   if (x == "enet"):
      module_env.Prepend(CPPPATH=["#thirdparty/enet/"])
      module_env.Append(CPPDEFINES=["MODULE_ENET_ENABLED"])
   elif (x == "websocket"):
      module_env.Append(CPPDEFINES=["MODULE_WEBSOCKET_ENABLED"])


module_env.add_source_files(env.modules_sources, src_files)

